### ISSUE TITLE
Later versions missing on central

### ISSUE THREAD

**Issue by SnoFox** [LapisPlugins/LapisCore#5]
The last version of LapisCore uploaded to Maven central is version 1.7.5, which makes it annoying to build and PR dependent plugins using current versions of LapisCore.

https://search.maven.org/artifact/net.lapismc/LapisCore

**Comment by Dart2112** [comment]
Sorry, it stopped getting updated when I switched to gradle

This has been fixed and it should now be deployed for each update from now on. In future you can build it and install it to your local maven repo as this is what I have been doing

**Comment by SnoFox** [comment]
Thank you!

I did end up working around it locally in for my CI, but thought you might want to know.
